application:
runtime: python27
api_version: 1
threadsafe: no

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?^node_modules/.*$


handlers:
- url: /static
  static_dir: static
  login: required

- url: /src
  static_dir: src
  login: required

- url: /build
  static_dir: build
  login: required

- url: /.*
  script: main.py
  login: required

libraries:
- name: webapp2
  version: latest
